<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIDMnZlI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIDMnZlI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIDMnZlI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIDMnZlI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIDMnZlI\App_KernelDevDebugContainer([
    'container.build_hash' => 'IDMnZlI',
    'container.build_id' => '0c1cca8f',
    'container.build_time' => 1745876911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIDMnZlI');
